Part18
peresvetjke/test_guru pull request #18
Opened 2021-10-20 07:30 UTC by peresvetjke

2021-10-20 16:50 UTC, BubuntuClu requested changes

2021-10-20 16:50 UTC, BubuntuClu commented on app/assets/javascripts/utilities/timer.js
> +        window.location.reload();
сделай сабмит формы, вместо перезагрузки страницы

2021-10-20 16:50 UTC, BubuntuClu commented on app/models/badge.rb
> +      new_badges << badge if badge.rule.condition_met?(passed_test_passage) &&
что за дикое условие? а если будут еще правила, оно еще хуже станет? надо что-то с этим придумать, чтобы с добавлением баджей не надо было дописывать в эту проверку ничего

2021-10-20 16:50 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :passed,          -> (user)           { joins(:users).where("users.id = :user_id AND test_passages.passed = true", user_id: user.id)}
название скоупа не совсем точно передает смысл кода. ты получаешь пройденные тесты пользователем

2021-10-20 16:50 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  scope :user,      -> (user)     {joins(:test).where('test_passages.user_id = :user_id', user_id: user.id)}
`TestPassage.user(user)` - вообще не понятно чего ожидать от такого метода. он должен вернуть мне пользователя?

2021-10-20 16:50 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  scope :category,  -> (category) {joins(:test).where('tests.category_id = :category_id', category_id: category.id)}
аналогично

2021-10-20 16:50 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  scope :level,     -> (level)    {joins(:test).where('tests.level = :level', level: level)}
аналогично

2021-10-20 16:50 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  attr_accessor :new_badges
это какой-то костыль. не стоит для объекта связанного с БД делать временное поле. при обновлении обьъекта этих данных не будет

2021-10-20 16:50 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def evaluate_result!
за выдачу баджей и проверку правил должен отвечать сервис, а не модель

2021-10-21 16:52 UTC, BubuntuClu requested changes

2021-10-21 16:52 UTC, BubuntuClu commented on app/controllers/admin/rules_controller.rb
> +    params.require(:rule).permit(:title, :category_id, :first_try, :all_tests, :level)
а если будут еще правила какие-то ты будешь новые поля добавлять? и в итоге у тебя будет мусор в таблице, где почти все строки пустые, а только парочка имеет значение. надо придумать другой подход

2021-10-21 16:52 UTC, BubuntuClu commented on app/services/badge_awarder.rb
> +    awarding = @test_passage.badges_awardings.create!(badge: badge, user: @test_passage.user)
строить логику на исключениях это плохое решение. значит ты что-то не так делаешь.

2021-10-21 16:52 UTC, BubuntuClu commented on app/services/badge_awarder.rb
> +      !all.empty? && all.ids.uniq.sort == passed.ids.uniq.sort
`!all.empty?` => `all.present?`

2021-10-21 16:52 UTC, BubuntuClu commented on db/migrate/20211018104531_create_rules.rb
> +      t.references :category, null: false, foreign_key: true
для правила хватит имя правила для отображения(если хочешь), имя правила для вызова метода проверки, значение параметра для правила

2021-10-21 16:52 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    TestPassage.category_and_user(self.test.category, self.user).select { |t| t.passed }.map { |t| t.test_id }.uniq.sort
нужно максимально использовать БД при получении данных. руби методов по обработке данных не должно использоваться, либо минимум

2021-10-21 16:52 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def tests_passed_ids_same_category
я бы вынес эти методы из модели и разместил в сервисе выдачи

2021-10-21 16:52 UTC, BubuntuClu commented on app/services/badge_awarder.rb
> +  def call
если сделать правило "легче" то метод `call` будет

```
Badge.all.each do |badge|
  user.badges << badge if send("#{badge.rule}_award?", badge.value) 
end
```

в проверку можешь еще добавить проверку на то был ли уже выдан такой бадж, но это не обязательно так как можно выдавать дубли

2021-10-22 05:49 UTC, peresvetjke commented on app/services/badge_awarder.rb
> +    awarding = @test_passage.badges_awardings.create!(badge: badge, user: @test_passage.user)
Конструкция user.badges << badge или user.badges.push классные - используем ассоциации. 

Проблема в том, что если ассоциаций больше одной, то как правильно записать - не знаю. 
Просто я еще к badge_awardings добавил test_passage_id (возможно, не правильно), чтобы в БД писать по итогам чего бэйджи были получены. Из-за этого перечисляю связи явно:
@test_passage.badges_awardings.create!(badge: badge, user: @test_passage.user).

Есть хороший способ?

Спасибо

2021-10-22 05:57 UTC, peresvetjke commented on app/services/badge_awarder.rb
> +    awarding = @test_passage.badges_awardings.create!(badge: badge, user: @test_passage.user)
А исключения решил убрать.

2021-10-22 16:49 UTC, BubuntuClu requested changes

2021-10-22 16:49 UTC, BubuntuClu commented on app/services/badge_awarder.rb
> +    passed = all.tests_passed_by_user(@test_passage.user)
ты можешь пройти 1 тест не из этого уровня. и потом пройти все тесты этого уровня. тогда у тебя `all` будет иметь на 1 тест больше чем нужно. условие проверки не сработает. тебе нужно отфильтровать пройденные тесты по уровню тоже

2021-10-22 16:49 UTC, BubuntuClu commented on db/migrate/20211018105227_remove_null_constraints.rb
> +class RemoveNullConstraints < ActiveRecord::Migration[6.1]
миллион лишних миграций. откати не нужные и удали. поправь создания таблиц. не надо захламлять папку миграций правками, когда их можно исправить. ты же в локальной ветке разработку ведешь, никто еще не подтнялу твои наработки, ты можешь делать с миграцями что угодно - накатывать/откатывать/править. пользуйся этим моментом

2021-10-22 16:49 UTC, BubuntuClu commented on app/services/badge_awarder.rb
> +    all = Test.where(category: category)
а как ты сохранишь объект в поле `value`? поле хранит `text`, значит скорее всего там название категории.
такой запрос тогда не подойдет, а подойдет тот, что делали в первых заданиях. найти тесты по названию категории

2021-10-22 16:49 UTC, BubuntuClu commented on app/services/badge_awarder.rb
> +    passed = all.tests_passed_by_user(@test_passage.user)
набор пройденных тестов, так же надо отфильтровать по заданной категории

2021-10-22 16:49 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  scope :test_passages_by_user_and_test, -> (user, test) { joins(:test).where("test_passages.user_id = ? AND tests.id = ?", user.id, test.id) }
не уверен что тянет на скоуп. ты его пока вызываешь один раз.
а зачем ты таблицу тестов джойнишь? test_id есть в пассаже

2021-10-23 06:14 UTC, peresvetjke commented on app/services/badge_awarder.rb
> +    passed = all.tests_passed_by_user(@test_passage.user)
> тогда у тебя all будет иметь на 1 тест больше чем нужно.

В методе пройденные пользователем (tests_passed_by_user) отфильтровываются из выборки тестов нужного уровня (all).

0) Было:
```
> all = Test.where(level: 2)
> all.ids
 => [2, 4] 
 
 > passed = all.tests_passed_by_user(User.find(1))
 > passed.ids
 => []
```
 
1) проходим 1 тест не из этого уровня (тест уровня 1, а не 2):
```
> reload!
> all = Test.where(level: 2)
> all.ids
=> [2, 4]
> passed = all.tests_passed_by_user(User.find(1))
> passed.ids
=> []
```

2) проходим тесты нужного уровня:
```
> reload!
> all = Test.where(level: 2)
> all.ids
=> [2, 4]
> passed = all.tests_passed_by_user(User.find(1))
> passed.ids
=> [2, 4]
```
Бэйдж присвоен.

При этом если выбирать тесты без учета уровня, то 
```
> all_passed = Test.tests_passed_by_user(User.find(1))
> all_passed.ids
=> [1, 2, 4]
```



Возможно, не правильно тебя понял - поправляй. Спасибо

2021-10-23 06:21 UTC, peresvetjke commented on app/services/badge_awarder.rb
> +    passed = all.tests_passed_by_user(@test_passage.user)
Ответил выше. 
(В текущей схеме нет возможности присвоить более одного правила бэйджам.) Но если выбираем по категории, как в указанном методе, то
all - определяются по критерию правила
passed - уже из них

2021-10-23 06:22 UTC, peresvetjke commented on app/models/test_passage.rb
> +  scope :test_passages_by_user_and_test, -> (user, test) { joins(:test).where("test_passages.user_id = ? AND tests.id = ?", user.id, test.id) }
понял

2021-10-23 06:22 UTC, peresvetjke commented on db/migrate/20211018105227_remove_null_constraints.rb
> +class RemoveNullConstraints < ActiveRecord::Migration[6.1]
Ок

2021-10-26 04:14 UTC, peresvetjke commented on app/services/badge_awarder.rb
> +    all = Test.where(category: category)
В поле value указываю именно id , а не title.

> а как ты сохранишь объект в поле value? 

```
class Rule < ApplicationRecord
  belongs_to :category, optional: true
```

Заменил тип value с текстового на integer.
Добавил валидации в модель правила. Теперь проверяем, что категория существует. 
[https://github.com/peresvetjke/test_guru/pull/18/commits/769698c7723e65cbc45625786e99be04d7fac43a#diff-436aa719a2915ff5a376c2310f9e24fe8f565a5de33c95bbe757408c6455c5cc](https://github.com/peresvetjke/test_guru/pull/18/commits/769698c7723e65cbc45625786e99be04d7fac43a#diff-436aa719a2915ff5a376c2310f9e24fe8f565a5de33c95bbe757408c6455c5cc)

2021-10-26 06:28 UTC, BubuntuClu commented on app/services/badge_awarder.rb
> +    all = Test.where(category: category)
как раз таки со строкой было правильно. только запрос ` all = Test.where(category: category)` был неправильный. нужно джойнить с категорией и в категории искать по названию. строковый параметр даст тебе больше гибкости чем числовой

2021-10-26 06:29 UTC, BubuntuClu commented on app/models/test.rb
> +  def self.test_ids_passed_by_category(category)
неиспользуемые методы

2021-10-26 13:39 UTC, peresvetjke commented on app/models/test.rb
> +  def self.test_ids_passed_by_category(category)
поправил, спасибо

2021-10-26 13:40 UTC, merged

2021-10-26 15:42 UTC, peresvetjke commented on app/services/badge_awarder.rb
> +    all = Test.where(category: category)
Строковой параметр гибче - ок. Но зачем это в случае категории?
При создании правила пользователь ведь не будет руками вводить название категории. 
1) Это даст ему возможность ошибиться и ввести не существующую. 
Можно добавить выбор категории из списка, если метод - категория. 
2) даже если он не ошибется, мы в value таблицы rules вряд ли хотим дублировать название категории (в categories она поменяется например, а в rules - нет).

А если в value сохраняется id, а не title категории, тогда зачем это?
> нужно джойнить с категорией и в категории искать по названию.

Спасибо