Part6
peresvetjke/test_guru pull request #6
Opened 2021-09-09 07:14 UTC by peresvetjke

2021-09-09 17:21 UTC, BubuntuClu requested changes

2021-09-09 17:21 UTC, BubuntuClu commented on app/models/question.rb
> +  validates :answers, length: { minimum: 1, maximum: 4 }
это не будет работать так как ты планируешь. проверял эту валидацию в консоле? получаешь ошибку при создании 5го ответа?

вообще валидация вызывается при сохранении объекта. когда ты добавляешь новый ответ, то вопрос не валидируется => валидация должна находиться не тут

2021-09-09 17:21 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :category_title, -> (category_title) { joins(:category).select('tests.title').distinct.where("categories.title = ?", category_title).order('tests.title DESC') }
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2021-09-09 17:21 UTC, BubuntuClu commented on app/models/user.rb
> +  scope :tests_by_level, -> (level) { Test.joins(:users).where("tests.level = ?", level) }
это не равно мерная замена метода, который был. как у тебя тут участвует текущий пользователь?
надо вернуть метод. кстати, заметил что он у тебя неправильно был сделан. тебе не надо джойнить пользователь, тебе нужна промежуточная таблица

2021-09-10 04:48 UTC, peresvetjke commented on app/models/test.rb
> +  scope :category_title, -> (category_title) { joins(:category).select('tests.title').distinct.where("categories.title = ?", category_title).order('tests.title DESC') }
Поправил.

2021-09-10 04:49 UTC, peresvetjke commented on app/models/user.rb
> +  scope :tests_by_level, -> (level) { Test.joins(:users).where("tests.level = ?", level) }
Вернул инстанс метод.

По поводу джойна пользователей. У меня есть промежуточная таблица - assessments, через нее идет джойн users к tests. Или как здесь надо?

2021-09-10 04:49 UTC, peresvetjke commented on app/models/question.rb
> +  validates :answers, length: { minimum: 1, maximum: 4 }
Проверял в консоли: 
https://docs.google.com/document/d/1cJLXj9C96CC03RdGMjRsA_GZpQMuYKQPttcEviwXZZk/edit?usp=sharing
Нужное кол-во ответов добавить в коллекцию или как это называется (создаю через question.answers.new), и только после этого вопрос и ответы можно сохранить. 

Если проверку перенести на этап создания ответа (подтверди плс), то если не ошибаюсь, не имеет смысла ограничение минимум 1 ответ?

2021-09-10 07:21 UTC, BubuntuClu commented on app/models/question.rb
> +  validates :answers, length: { minimum: 1, maximum: 4 }
ну, таким образом ответы не будут создаваться, они будут создаваться по одному.

>Если проверку перенести на этап создания ответа (подтверди плс), то если не ошибаюсь, не имеет смысла ограничение минимум 1 ответ?

да, минимальное количество нет смысла проверять

2021-09-10 07:22 UTC, BubuntuClu commented on app/models/user.rb
> +  scope :tests_by_level, -> (level) { Test.joins(:users).where("tests.level = ?", level) }
тут достаточно только `assessments` сджойнить. там есть вся нужная информация для этого запроса

2021-09-10 07:24 UTC, BubuntuClu commented on app/models/test.rb
> +    Test.category_title(category_title).select('tests.title').distinct.order('tests.title DESC').pluck('tests.title')
`select` можно убать, так как ты делаешь `pluck`

2021-09-10 07:24 UTC, BubuntuClu commented on app/models/user.rb
> +    User.test_level(level).where("assessments.user_id = ?", id)
тут не будет вызова скоупа.

вообще тут все заменяется на `tests.where(level: level)` - посмотри как работает этот запрос
либо напиши свой через Test+Assesments

2021-09-10 15:13 UTC, peresvetjke commented on app/models/user.rb
> +    User.test_level(level).where("assessments.user_id = ?", id)
> `tests.where(level: level)` - посмотри как работает этот запрос

джойнит через assessments и сам подставляет user_id. здорово!
Обновил.

2021-09-10 17:53 UTC, BubuntuClu commented on app/models/answer.rb
> +  validates_with MyValidator
можно не через класс, а через кастомную валидацию 
```
validate :max_answer_per_question, on: :create

def max_answer_per_question
....
```

2021-09-17 12:15 UTC, merged